---
  - name: Install epel-release
    yum:
      name: epel-release 
      state: installed

  - name: Install certbot
    yum:
      name: certbot 
      state: installed

  - name: Install python2-certbot-nginx
    yum:
      name: python2-certbot-nginx 
      state: installed

  # - name: Stop Nginx
  #   systemd:
  #     name: nginx
  #     state: stopped
  
  - name: Create Certificates
    command: certbot certonly --agree-tos --nginx --cert-name {{ letsencrypt_name }} --email {{ letsencrypt_mail }} -n -d {{ gitea_domain }} {{ gitea_domain_aliases | map('regex_replace', '^(.*)$', '-d \1') | join(' ') }}
  
  - name: Delete Cert Files
    file:
      state: absent
      path: "{{ item }}"
    with_items:
    - "{{ nginx_ssl_cert_crt }}"
    - "{{ nginx_ssl_cert_key }}"
    - "{{ nginx_ssl_csr }}"

  - name: Symlink Cert
    file:
      src: "/etc/letsencrypt/live/{{ letsencrypt_name }}/cert.pem"
      dest: "{{ nginx_ssl_cert_crt }}"
      state: link

  - name: Symlink Key
    file:
      src: "/etc/letsencrypt/live/{{ letsencrypt_name }}/privkey.pem"
      dest: "{{ nginx_ssl_cert_key }}"
      state: link

  - name: Restart Nginx
    systemd:
      name: nginx
      state: restarted

  - name: Copy letsencrypt renew script
    template:
      src: templates/letsencrypt.sh.j2
      dest: "{{ gitea_bin_dir }}/letsencrypt.sh"
      owner: "{{ gitea_service_user }}"
      group: "{{ gitea_service_group }}"
      mode: '0750'

  - name: Creates a cron file under /etc/cron.d
    cron:
      name: Renew Let's Encrypt
      minute: "0"
      hour: "0,12"
      user: "{{ gitea_service_user }}"
      job: "{{ gitea_bin_dir }}/letsencrypt.sh > /dev/null"
      cron_file: letsencrypt-renew

    
...
